### ISSUE TITLE
Panic when publishing

### ISSUE THREAD

**Issue by dahankzter** [nats-io/go-nats#192] opened 2016-06-02 09:29 UTC
I saw this by accident and have no idea really why. Just thought I would drop it here.

``` bash
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 249599 [running]:
panic(0x7eba60, 0xc83d589f70)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*WaitGroup).Wait(0xc8200598e8)
    /usr/local/go/src/sync/waitgroup.go:129 +0x114
github.com/nats-io/nats.(*Conn).waitForExits(0xc820059800)
    /data/jenkins/jobs/tgm_ng deploy/workspace/vendor/src/github.com/nats-io/nats/nats.go:733 +0x6a
github.com/nats-io/nats.(*Conn).doReconnect(0xc820059800)
    /data/jenkins/jobs/tgm_ng deploy/workspace/vendor/src/github.com/nats-io/nats/nats.go:1084 +0x25
created by github.com/nats-io/nats.(*Conn).processOpErr
    /data/jenkins/jobs/tgm_ng deploy/workspace/vendor/src/github.com/nats-io/nats/nats.go:1232 +0x25f
```

**Comment by derekcollison** [comment] 2016-06-02 15:09
Thanks, will take a look.

**Comment by kozlovic** [comment] 2016-06-02 15:29
Would you please tell us what exact version you are using? Also, do you have the full stack by any chance? Thanks!

**Comment by kozlovic** [comment] 2016-06-02 15:39
Also, which Go version are you using?

**Comment by kozlovic** [comment] 2016-06-02 16:15
Ok, I wrote a non-NATS test case just to reproduce the error to understand better what's going on:

```
var wg sync.WaitGroup

func release() {
	wg.Done()
}

func TestIvan(t *testing.T) {
	for i := 0; i < 1000000; i++ {
		wg.Add(1)
		go release()
		go func() {
			for {
				wg.Add(1)
				wg.Done()
			}
		}()
		wg.Wait()
	}
}
```
Running this will quickly produce the panic above or another type: `panic: sync: WaitGroup misuse: Add called concurrently with Wait`.

Digging more.

**Comment by dahankzter** [comment] 2016-06-02 21:11
go version go1.6.2 darwin/amd64

I am sorry but I don't have the entire stack. I think the supervisord logging rolled them out... :(
What happens is basically a large number of request/reply communications between several nodes in high frequency. Payload is sometimes large but the common case fits in the default max size.
A single nats connection is used concurrently in a controlled relatively small number number of goroutines. I was under the impression that that is the way to do it. Hope I got that right.

Nats is currently in a two node cluster and no slow consumers reported during normal operation, just on app restarts.

Is there anything else I can help with or test?

**Comment by kozlovic** [comment] 2016-06-02 21:19
Thanks. I don't think there is anything wrong with what you are doing. Have you noticed disconnects? Maybe a server restarted?
Also, which NATS client and server versions are you using? Thanks!

**Comment by dahankzter** [comment] 2016-06-02 21:26
No disconnects that I can see other than "controlled" ones such as during deploys etc.
Nothing while the apps are running.

nats-server version 0.8.0
from gnatsd-v0.8.0-linux-amd64.zip

**Comment by kozlovic** [comment] 2016-06-02 21:32
What about the client version? The stack shows that the client was trying to reconnect after processing an error. It can be after a socket read error, a parsing error or few other places. Unfortunately, we don't see what's the trigger. If you have restarted one of the server, that could be a valid reason for the client to try to reconnect.

**Comment by dahankzter** [comment] 2016-06-02 21:38
Client is from this version: 68e8b83fcd7d9bf07b42aa7218039823b0972853
I am using Gb to manage dependencies and that is the vendored version.

It may very well be that that is the case. The services was in heavy flux with lots of deploys. I was trying to be structured but it is possible that disconnects happen.

If that is the only obviously reasonable explanation judging from the code then it is probably it.
I only saw it once and though it may have happened earlier it did not happen later during high load as well.

**Comment by kozlovic** [comment] 2016-06-02 21:41
Ok thanks! I am sorry I don't find this commit from `git log` on master. Could you double check?

**Comment by dahankzter** [comment] 2016-06-02 21:45
Actually that commit was from the server that also gets pulled in.

fc85f44c1659ab6610d76fd6bd0e44ad2cadf697 should be the one.

**Comment by kozlovic** [comment] 2016-06-02 21:53
Thanks. I have never seem this issue myself, and I have been running a lot of tests with reconnects. Also, as far as I know, this has never been reported. So you may not see that again.
Still, I think we could change the code to avoid re-use of the wait group used to make sure some of the go-routines are finished before proceeding. I will keep you posted.

**Comment by dahankzter** [comment] 2016-06-03 06:11
Thx!

**Comment by kozlovic** [comment] 2016-06-03 20:26
I may have to retract my previous comment because I am not really sure how this can happen. Would you agree to wait an see if you can reproduce and hopefully get the full stack to see if it gives me more clue on what's happening? As of now, for a given connection, I am not sure how we can have 2 `waitForExit` calls (or even a parallel execution of `wg.Add`) for a given connection.

**Comment by dahankzter** [comment] 2016-06-04 06:40
Sure no problem. Once this is properly integrated with the log collection I
can put a trigger on panics.

**Comment by kozlovic** [comment] 2016-06-06 16:09
Just curious, are you setting your client's PingInterval to a rather low value? Do you know if this app seem to have been otherwise communicating with the server without any issue at the time of the panic? In other words, was there inbound/outbound traffic when that happened?

**Comment by kozlovic** [comment] 2016-06-13 12:52
Closing for now. Don't hesitate to re-open if you have more info or, if you can reproduce, the full stack trace. Thanks!

**Comment by petemiron** [comment] 2017-03-06 13:22
New report from Google Groups:
encountered a panic in one of my NATS clients:

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 372091 [running]:
sync.(*WaitGroup).Wait(0xc420499328)
       /usr/local/go/src/sync/waitgroup.go:133 +0xd8
github.com/nats-io/go-nats.(*Conn).waitForExits(0xc420499200)
       /XXX/src/github.com/nats-io/go-nats/nats.go:825 +0x6a
github.com/nats-io/go-nats.(*Conn).spinUpGoRoutines(0xc420499200)
       /XXX/src/github.com/nats-io/go-nats/nats.go:835 +0x2f
created by github.com/nats-io/go-nats.(*Conn).processConnectInit
       /XXX/github.com/nats-io/go-nats/nats.go:919 +0x1a9
```

It seems like I have had the same problem described here (almost 10 months old, ticket closed): https://github.com/nats-io/go-nats/issues/192. I don't have the full stack that occurred either.

I believe this is related to my STAN server being restarted and also that my client is configured to reconnect infinitely, but I can't be sure without full trace:

```
config := nats.Options{
  MaxReconnect: -1,
}
```

My questions:
Is this a really rare panic ? I see the github ticket is closed, but yet I encountered the panic. Is there anything to do to avoid that panic ?
Is MaxReconnect: -1 the best way to have infinite reconnect try ?

**Closed** 2017-03-07 17:17 UTC
Labels: waffle:needs review
