### ISSUE TITLE
go-nats panic 

### ISSUE THREAD

**Issue by shengery** [nats-io/go-nats#367] opened 2018-05-30 14:09 UTC
Versions of gnatsd and affected client libraries used:
```
gnatsd v1.0.4 download from github release binary
client library version 1.3.1
```
OS/Container environment:
CentOS 6.8 64Bit bare VM

Steps or code to reproduce the issue:
gnatsd is run with single node
The go *nats.Conn is used in multiple goroutines, each of which may publish message and pushsrv subscribe 6 topics with the same connection.
When there are a lot of concurrent users login into the service , the pushsrv panic with the below message :

panic: sync: negative WaitGroup counter

goroutine 9291 [running]:
sync.(*WaitGroup).Add(0xc42121a530, 0xffffffffffffffff)
 /usr/local/go/src/sync/waitgroup.go:75 +0x134
sync.(*WaitGroup).Done(0xc42121a530)
 /usr/local/go/src/sync/waitgroup.go:100 +0x34
pushsrv/vendor/github.com/nats-io/go-nats.(*Conn).readLoop(0xc4200b6a00, 0xc42121a530)
 /data/home/go_workspace/src/pushsrv/vendor/github.com/nats-io/go-nats/nats.go:1554 +0x238
created by pushsrv/vendor/github.com/nats-io/go-nats.(*Conn).spinUpGoRoutines
 /data/home/go_workspace/src/pushsrv/vendor/github.com/nats-io/go-nats/nats.go:979 +0xb1

**Comment by kozlovic** [comment] 2018-05-30 19:48
I had fixed  a similar issue in 1.3.0, so I will have another look. In the meantime, could you check for me the go client details? There is no 1.3.1, and I looked at few of the releases and the line numbers don't match any.
Again, I am going to try to write a test that can reproduce, but would love some clarification on the client version you are using. Alternatively, I see that you are vendoring: have you tried to update your vendor go-nats directory with the latest release?

**Comment by shengery** [comment] 2018-05-31 02:57
Thanks kozlovic,
There is not a release version named 1.3.1 really in the release category. I clone the client library via ```go get``` command in the 2017, I found there is a constant in value Version in the nats.go
```go 
package nats

import (
	"bufio"
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"math/rand"
	"net"
	"net/url"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/nats-io/go-nats/util"
	"github.com/nats-io/nuid"
)

// Default Constants
const (
	Version                 = "1.3.1"
	DefaultURL              = "nats://localhost:4222"
	DefaultPort             = 4222
	DefaultMaxReconnect     = 60
	DefaultReconnectWait    = 2 * time.Second
	DefaultTimeout          = 2 * time.Second
	DefaultPingInterval     = 2 * time.Minute
	DefaultMaxPingOut       = 2
	DefaultMaxChanLen       = 8192            // 8k
	DefaultReconnectBufSize = 8 * 1024 * 1024 // 8MB
	RequestChanLen          = 8
	LangString              = "go"
)

// STALE_CONNECTION is for detection and proper handling of stale connections.
const STALE_CONNECTION = "stale connection"
...
```
Later  last night when we were running stress testing on another imsrv, which is using the same copy of the nats client, there was an other panic stack info 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8763a1]

goroutine 62661 [running]:
imsrv/vendor/github.com/nats-io/go-nats.(*Conn).parse(0xc4200bea00, 0xc42591e000, 0x8000, 0x8000, 0x8000, 0x0)
 /data/home/user_00/go_workspace/src/imsrv/vendor/github.com/nats-io/go-nats/parser.go:278 +0xe61
imsrv/vendor/github.com/nats-io/go-nats.(*Conn).readLoop(0xc4200bea00, 0xc423975e10)
 /data/home/user_00/go_workspace/src/imsrv/vendor/github.com/nats-io/go-nats/nats.go:1545 +0x1d0
created by imsrv/vendor/github.com/nats-io/go-nats.(*Conn).spinUpGoRoutines
 /data/home/user_00/go_workspace/src/imsrv/vendor/github.com/nats-io/go-nats/nats.go:979 +0xb1
```

**Comment by derekcollison** [comment] 2018-05-31 05:30
We will look into it for sure, but we do recommend using a formal release. If possible use the latest release found here: https://github.com/nats-io/go-nats/releases/tag/v1.5.0

**Comment by kozlovic** [comment] 2018-05-31 13:34
@shengery These are really strange crashes. Would you mind showing how you create the NATS connection and give us as much information as possible as how you use it? Thanks!

**Comment by kozlovic** [comment] 2018-06-01 15:02
Thanks. Need to dig more into that, but still very confused with the stack. For instance, from your original report, we see that:
```
goroutine 9291 [running]:
sync.(*WaitGroup).Add(0xc42121a530, 0xffffffffffffffff)
/usr/local/go/src/sync/waitgroup.go:75 +0x134
sync.(*WaitGroup).Done(0xc42121a530)
/usr/local/go/src/sync/waitgroup.go:100 +0x34
pushsrv/vendor/github.com/nats-io/go-nats.(*Conn).readLoop(0xc4200b6a00, 0xc42121a530)
/data/home/go_workspace/src/pushsrv/vendor/github.com/nats-io/go-nats/nats.go:1554 +0x238
```
Yet, you can see that from the 1.3.0 tag, this line has nothing to do with the report:
[nats.go line 1554](https://github.com/nats-io/go-nats/blob/v1.3.0/nats.go#L1554)

The line should point to something like [this](https://github.com/nats-io/go-nats/blob/v1.3.0/nats.go#L1489).

**Comment by shengery** [comment] 2018-06-05 03:15
hi @kozlovic , the commit in my vendor repository should be at the commit a2b049bedd9f04e9c033655e7ad7dc8404d44aa2 
I put the client library via ```go get ``` command , not directly download the release version .

**Comment by shengery** [comment] 2018-06-08 03:46
hi @kozlovic , is there any further investigation ?

**Comment by kozlovic** [comment] 2018-06-11 15:44
Sorry for the delay, I was on vacation. I may refactor a bit the code around that for a fix to #368, but not sure what the problem for this issue is since the rare panic due to waitgroup was already fixed (or at least an attempt to) in 1.3.0.
Have you had a chance to try yourself with the latest release?

**Comment by shengery** [comment] 2018-06-12 06:51
@kozlovic thanks for your reply
We are currently using the latest release version , the problem has not shown yet.

**Comment by kozlovic** [comment] 2018-08-07 17:36
Closing for now.. we will re-open if you have some updates.

**Closed by kozlovic** 2018-08-07 17:36 UTC
